apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-http-producer
  name: kafka-http-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-http-producer
    spec:
      containers:
      - name: kafka-http-producer
        image: ppatierno/kafka-http-producer:latest
        env:
          - name: HOSTNAME
            value: my-bridge-bridge-service
          - name: PORT
            value: "8080"
          - name: TOPIC
            value: my-topic
          - name: SEND_INTERVAL
            value: "1000"